### ISSUE TITLE
提示“认证失败”

### ISSUE THREAD

**Issue by lucky-wavespider** [hdfg159/aria2-nginx-alpine-webui#2]
web上弹出“认证失败”

**Comment by hdfg159** [comment]
@lucky-wavespider 需要配置自定义密钥，默认密码是hdfg159-download，配置完成在AriaNG Web网页【系统设置-AriaNg设置】设置你配置的密钥
详细见配置，修改该配置就行了：
https://github.com/hdfg159/aria2-nginx-alpine-webui/blob/6094cba11bc0d5a8ec6d7b39351fee482ed7646c/aria2.conf#L11
